# Generated by Django 3.1.4 on 2020-12-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplateSwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigTemplateTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configtemplateswitchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('tpl_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configtemplatetablemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigTemplateValueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(max_length=254)),
                ('required', models.BooleanField()),
                ('type', models.CharField(choices=[('i', 'i'), ('f', 'f'), ('p', 'p'), ('s', 's'), ('b', 'b')], max_length=1)),
                ('default_value', models.CharField(blank=True, max_length=254, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway_proxy_core.configtemplatetablemodel')),
            ],
        ),
        migrations.AddField(
            model_name='configtemplateswitchmodel',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway_proxy_core.configtemplatetablemodel'),
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_config', models.JSONField()),
                ('config_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway_proxy_core.configtypemodel')),
            ],
        ),
    ]
