# Generated by Django 3.1.4 on 2020-12-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplatevaluemodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configtemplatetablemodel',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configtemplatevaluemodel'),
        ),
        migrations.AlterField(
            model_name='configtemplatevaluemodel',
            name='type',
            field=models.CharField(choices=[('i', 'i'), ('f', 'f'), ('p', 'p'), ('s', 's'), ('b', 'b'), ('c', 'c')], max_length=1),
        ),
        migrations.DeleteModel(
            name='ConfigTemplateSwitchModel',
        ),
    ]
