# Generated by Django 3.1.4 on 2020-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0002_auto_20201205_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplatetablemodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
