# Generated by Django 3.1.4 on 2020-12-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0004_configtemplatetablemodel_have_sub_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configtemplatetablemodel',
            unique_together={('name', 'switch')},
        ),
    ]
