# Generated by Django 3.1.4 on 2020-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0005_auto_20201206_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplatetablemodel',
            name='ns',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configtemplatevaluemodel',
            name='ns',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
