# Generated by Django 3.1.4 on 2020-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0006_auto_20201206_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtemplatetablemodel',
            name='ns',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='configtemplatevaluemodel',
            name='ns',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='configtemplatetablemodel',
            unique_together={('ns', 'name', 'switch')},
        ),
    ]
