# Generated by Django 3.1.4 on 2020-12-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0007_auto_20201217_1401'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='ConfigTemplateTableModel',
            new_name='ConfigStructSchemaGroupModel',
        ),
        migrations.RenameModel(
            old_name='ConfigTemplateValueModel',
            new_name='ConfigStructSchemaItemModel',
        ),
    ]
