# Generated by Django 3.1.4 on 2020-12-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0010_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configstructschemagroupmodel',
            old_name='ns',
            new_name='ns_old',
        ),
        migrations.RenameField(
            model_name='configstructschemaitemmodel',
            old_name='ns',
            new_name='ns_old',
        ),
        migrations.AlterUniqueTogether(
            name='configstructschemagroupmodel',
            unique_together={('ns_old', 'name', 'switch')},
        ),
        migrations.AddField(
            model_name='configstructschemagroupmodel',
            name='ns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gateway_proxy_core.configstructschemanamespacemodel'),
        ),
        migrations.AddField(
            model_name='configstructschemaitemmodel',
            name='ns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='gateway_proxy_core.configstructschemanamespacemodel'),
        ),
    ]
