# Generated by Django 3.1.4 on 2020-12-17 15:24

from django.db import migrations, models
import django.db.models.deletion
import gateway_proxy_core.models._mixin


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0012_remove_and_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigComponentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('n', 'n'), ('s', 's'), ('b', 'b'), ('l', 'l'), ('d', 'd')], max_length=1)),
                ('vue_component', models.CharField(max_length=254)),
            ],
            bases=(gateway_proxy_core.models._mixin.ModelNameStrTrainMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigValidatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            bases=(gateway_proxy_core.models._mixin.ModelNameStrTrainMixin, models.Model),
        ),
        migrations.AddField(
            model_name='configstructschemaitemmodel',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configcomponentmodel'),
        ),
        migrations.AddField(
            model_name='configstructschemaitemmodel',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configvalidatormodel'),
        ),
    ]
