# Generated by Django 3.1.4 on 2020-12-17 16:04

from django.db import migrations, models
import django.db.models.deletion
import gateway_proxy_core.models._mixin


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0013_add_validator_and_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigStructSchemaDataTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            bases=(gateway_proxy_core.models._mixin.ModelNameStrTrainMixin, models.Model),
        ),
        migrations.AddField(
            model_name='configstructschemaitemmodel',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configstructschemadatatypemodel'),
        ),
        migrations.AddField(
            model_name='configtypemodel',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configstructschemadatatypemodel'),
        ),
        migrations.AddField(
            model_name='configvalidatormodel',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway_proxy_core.configstructschemadatatypemodel'),
        ),
    ]
