# Generated by Django 3.1.4 on 2020-12-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_proxy_core', '0014_auto_20201217_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configtypemodel',
            old_name='tpl_table',
            new_name='tpl_schema',
        ),
    ]
